language: android

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # When chaning the following, change also in build.gradle!
    - build-tools-25.0.0
    - android-24

    - extra-android-m2repository

before_install:
# Avoid ./gradlew: Permission denied
 - chmod +x gradlew
 # Access licenses for Android SDK Build-Tools
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew clean assembleRelease --stacktrace
