language: android

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # When chaning the following, change also in build.gradle!
    - build-tools-25.0.0
    - android-24

    - extra-android-m2repository

before_install:
# Avoid ./gradlew: Permission denied
 - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew clean assembleRelease --stacktrace
